rust/ares/src/interpreter.rs, rust/ares/src/main.rs, rust/ares/src/mem.rs, rust/ares/src/noun.rs
This includes a bugfix in the allocator, basic printing functions for nouns, and renames the axis function to slot because having the verb and noun named the same was awkward.
=> Fixes and printing functions

rust/ares/src/mem.rs
This simplifies the unifying equality implementation, removes some redundant tests, and adds a generous comment explaining the implementation and how it differs from vere.
- Make raw equality the outermost check
- Don't do anything explicity for direct atoms: equal direct atoms will pass the raw equality check: disequal direct atoms will fail it and should be allowed to fall through the type discrimination
- Don't check pointer equality on indirect atoms or cells as that was already done by the raw equality check.
=> [ares][unifying equality] simplify, document, remove bugs and redundancies

rust/ares/src/noun.rs
We already added 2 to the buffer in new_raw_mut, no need to do it again.  This fixed a bug in something I was tinkering with.
=> [ares] fix atom initialization bug

rust/ares/src/noun.rs
I have found these constructors convenient, otherwise writing out even small nouns is very long.  Arguably `new_tuple` should be `C` or something.
=> [ares] convenient noun constructors

rust/nix/sources.json
This updates nixpkgs to track 22.11 which results in a rust compiler upgrade in shells started from shell.nix
=> [ares] update rust compiler to 1.64

rust/ares/src/mem.rs
Should only check that the data is equal, instead of running off into the following memory by two words.
=> [ares] fix bug in unifying equality

rust/ares/src/interpreter.rs
Relatively deep edits were producing incorrect results.
=> [ares] fix bug in edit()

rust/ares/src/mem.rs
The addition/subtraction is with respect to the polarity we matched on, but the high and low pointers are with respect to the polarity we're switching to.  The stack pointer is always at slot 0 (the outer slot) and the frame pointer is always at slot 1 (the inner slot).
This allows the "run a bunch of L2 events" test to pass.
=> [ares] fix the Last Bug in unifying equality

rust/ares/Cargo.lock, rust/ares/Cargo.toml, rust/ares/src/interpreter.rs, rust/ares/src/jets/math.rs, rust/ares/src/lib.rs, rust/ares/src/main.rs, rust/ares/src/mem.rs, rust/ares/src/noun.rs
This pairs with https://github.com/tczajka/ibig-rs/compare/main...urbit:ibig-rs:main to patch ibig-rs to use the nock stack for all allocations (for the operations we use).  The patch to ibig-rs is fairly invasive, but I don't know an easier way.
This includes the assert-no-alloc crate and ties it to the interpreter and jet tests, so that it will crash if we allocate at times when we're not supposed to.  This was useful for testing, and I think we should leave it on, since it gets compiled out of releases anyway.  If this crash is annoying you (eg because your printf allocates), just comment out the custom allocator in lib.rs.
This is not quite optimal for the number of copies from atoms to ubig and vice versa, but it's better than before.  Before, going from ubig to an atom required two …
=> Use patched ibig to do all allocations on nock stack

.github/workflows/ares-shared.yml, rust/ares/benches/cue_pill.rs, rust/ares/src/hamt.rs, rust/ares/src/interpreter.rs, rust/ares/src/jets.rs, rust/ares/src/jets/math.rs, rust/ares/src/main.rs, rust/ares/src/mem.rs, rust/ares/src/newt.rs, rust/ares/src/noun.rs, rust/ares/src/serf.rs, rust/ares/src/serialization.rs, rust/ares/src/snapshot.rs, rust/shell.nix
This PR cleans up (most of) the code flagged by Rust's linter, `cargo clippy`. A large number of `warning: unsafe function's docs miss `# Safety` section` lints remain, which we should address. Reasoning about undefined behavior in Rust is significantly harder than in C since safe Rust makes so many more assumptions than C does; unsafe Rust code, therefore, must be aware of the implications of its unsafe behavior for safe Rust code. Documenting all `unsafe` blocks with a quick justification of why the particular `unsafe` block is in fact safe and why it's necessary will make it easier to understand the code and to track down bugs related to `unsafe` blocks.
=> Address (most) lints suggested by `cargo clippy`

rust/ares/src/noun.rs, rust/ibig-rs/src/add_ops.rs, rust/ibig-rs/src/buffer.rs, rust/ibig-rs/src/convert.rs, rust/ibig-rs/src/div_ops.rs, rust/ibig-rs/src/memory.rs, rust/ibig-rs/src/mul_ops.rs
This PR replaces dynamic trait objects with static type parameters to eliminate the overhead of a vtable lookup at runtime. It does by requiring types implementing the `NounAllocator` or `Stack` traits also implement the [`Sized`](https://doc.rust-lang.org/std/marker/trait.Sized.html) trait. This change does not result in an increase in binary size:
```
$ git checkout status
$ cargo build --release
$ du -sh target/release/libares.rlib
1.1M    target/release/libares.rlib
$ git checkout peter/remove-dyn
$ cargo build --release
$ du -sh target/release/libares.rlib
1.1M    target/release/libares.rlib
```
=> Replace dynamic trait objects with static type parameters

rust/ares/src/jets.rs, rust/ares/src/jets/math.rs, rust/ares/src/noun.rs
Hello! Finally got time to finish this up.
- Added jet for `rev`.
- Added utility functions for mutable access to noun bits.
- Rewrote `from_ubig` to not have that long chain of bitshifts, as I was bored on the plane back home.
I don't consider this fully done. Most notably:
- Tests need to be improved.
- Is it okay for nouns to have leading zero bytes? This could come up with direct manipulation to noun's bits, and mutable access functions allow for that.
- Should this go to a different module?
One thing I wanted to ask, is there a nice way to generate test cases? I would imagine basing expectations on known good implementation (vere) would be a good idea.
=> Add rev jet

rust/ares/src/pma/.gitignore, rust/ares/src/pma/README.md, rust/ares/src/pma/includes/checksum.c, rust/ares/src/pma/includes/checksum.h, rust/ares/src/pma/makefile, rust/ares/src/pma/malloc.c, rust/ares/src/pma/malloc.h, rust/ares/src/pma/test/sanity.c
This PR moves the PMA code, and therefore the active development of the PMA, into Ares. The code is synced from [ashelkovnykov/pma_malloc, commit hash 3329657abccdd06a65d21395e338343289c99ce9](https://github.com/ashelkovnykov/pma_malloc/tree/3329657abccdd06a65d21395e338343289c99ce9).
I have replaced the existing `README` with a temporary one which will be updated once the final design of the PMA is in the code, since a great deal of the current `README` is an explanation of why I used Arrays instead of B Trees.
Note that this PR is *before* applying Phil's patch, therefore there is another PR for the PMA coming shortly.
Some questions:
- What should be done about the licenses? LMDB is OpenLDAP and `phk_malloc` is "beerware". How does this square with MIT?
- I've kept the structure of the …
=> Move PMA code into Ares from separate repo

rust/ares/Cargo.toml, rust/ares/src/mug.rs
the name of murmur3_32_nocopy was changed to murmur3_32_of_slices but to avoid breaking things we're just going to target the last commit where its called murmur3_32_nocopy
=> cargo: murmur3 target specific commit

.github/workflows/ares-shared.yml, rust/ares/build.rs, rust/ares/src/mem.rs, rust/ares/src/pma/malloc.c, rust/ares/src/pma/test/internals.h, rust/ares/src/pma/test/malloc.c, rust/ares/src/snapshot/pma.rs
**Summary:**
Unit tests for the PMA C module
**Unimplemented tests:**
In conversation on July 19-20, 2023, the decision to remove the PHK aspects of the PMA from the design was reconfirmed. This means that there are now two upcoming refactors to the PMA: the switch from an Array-based page directory to a B+ Tree page directory, and the switch to pages as the smallest unit of persistent allocation. As such, unit tests for the following functions were skipped:
- `_pma_malloc_bytes`
- `_pma_write_page_offset`
- `_pma_write_page_status`
- `_pma_sync_dirty_pages`
The following logic, which would otherwise be tested in `pma_load`, is not:
- Syncing unsynced changes to the page directory upon load after a crash
- Correctly computing the free page and free page run caches
- Correctly not joining …
=> Unit tests for the PMA

rust/ares/src/mem.rs
Addresses #73 
I didn't realize this extra set of parentheses was doing any work tbh. Guess I need to review precedence order with the pointer interface.
=> copy() memory issue fix

rust/ares/src/interpreter.rs, rust/ares/src/lib.rs, rust/ares/src/main.rs
Can be tested with the patch:
```patch
diff --git a/rust/ares/src/jets/math.rs b/rust/ares/src/jets/math.rs
index 9993cb0..2882291 100644
--- a/rust/ares/src/jets/math.rs
+++ b/rust/ares/src/jets/math.rs
@@ -67,6 +67,16 @@ pub fn jet_add(stack: &mut NockStack, subject: Noun) -> Result<Noun, JetErr> {
let a = raw_slot(arg, 2).as_atom()?;
let b = raw_slot(arg, 3).as_atom()?;
+    eprintln!("AAAAAHHHH I'M ALLOOOOOOCATING");
+
+    let mut v : Vec<u64> = Vec::with_capacity(0);
+
+    v.push(1);
+    v.push(2);
+    v.push(3);
+
+    eprintln!("ALLOOOOOOCATED. Element 3: {}", v[2]);
+
if let (Ok(a), Ok(b)) = (a.as_direct(), b.as_direct()) {
Ok(Atom::new(stack, a.data() + b.data()).as_noun())
} else {
```
=> main: make assert_no_alloc actually assert

rust/ares/src/mem.rs
if these functions are callled with a non-empty lightweight stack, they will try to pop things that they shouldn't.
all other stack_is_empty() callsites happen in a fresh stack frame, so we already know the lightweight stack will be empty.
This would have made detecting the problem that #84 resolves take a few minutes instead of a few hours.
=> mem: assert stack_is_empty() when it should be

rust/ares/Cargo.toml
Using patch.crates-io does not work because it only applies to the local crate development and not as a setting for consumers of the package
Thanks to @drbeefsupreme for the original fix
=> ares: make ibig dep a relative path so importing as a crate works properly

rust/ares/src/hamt.rs
This was using the lightweight stack, but this presented the following issue: `NockStack::copy()` can be called during the `Hamt::preserve()` call, and the lightweight stack may not be empty. `NockStack::copy()` presumes that the lightweight stack is empty when it is called, and thus tried to pop elements that `preserve()` had pushed onto it.
`NockStack::copy()` should probably assert that the lightweight stack is empty when its called.
I'm making the assert `stack_is_empty()` a separate PR #85 since its a separate concern, but I have tested that it works fine with this PR and several jamfiles where `copy()` is called many times.
=> hamt: preserve() traversal_stack uses rust stack

rust/ares/src/mem.rs
This fixes a bug in unifying equality that prevented it from ever properly discovering pointer seniority and caused us to chaotically introduce pointers to junior memory.
Credit to @ashelkovnykov for his tireless work narrowing this down, @drbeefsupreme for very helpful additional reproductions and other assistance, and @joemfb for finally spotting the actual bug.
@ashelkovnykov please verify that this is a fix for #87
=> unifying equality: fix senior_pointer_first

rust/ares/src/main.rs, rust/ares/src/snapshot/double_jam.rs
`write_bytes` takes a number of word-sized entries, not a number of bytes.
=> Fix loading from snapshot

rust/ares/src/noun.rs
This implements as_bytes() on Atom so you can handle direct and indirect atoms the same. For both it returns a reference to the underlying data as &[u8].
=> implement as_bytes() on Atom

rust/ares/src/interpreter.rs
This replaces the `local_noun_pointer()` calls, which are not correct in the new, tail-recursive interpreter, with the saved formula from the NockWork stack entry.
=> interpreter: fix memo hints

.github/workflows/ares-shared.yml, rust/ares/Cargo.toml, rust/ares/src/interpreter.rs, rust/ares/src/mem.rs, rust/ares/src/mug.rs, rust/ares/src/noun.rs
Adds assertion macros controlled by Rust feature flags to vital functions in `interpreter.rs`, `mem.rs`, and `mug.rs`. These assertions were useful for debugging during the `NockStack` incident.
@eamsden Perhaps they should all be enabled for CI?
=> Add debug assertions from NockStack investigation

rust/ares/src/mem.rs
Resets the NockStack. We'll need this for the PMA eventually, but Zorp also needs this right now.
=> mem: add reset() for NockStack

rust/ares/src/noun.rs
Necessary for floating-point; nice for conversions from direct atoms.
In particular, I'd like this expedited to complete `last` in the parsing jets.
=> Add u64/u128 atom exports

rust/ares/Cargo.lock, rust/ares/Cargo.toml, rust/ares/src/interpreter.rs, rust/ares/src/jets.rs, rust/ares/src/jets/bits.rs, rust/ares/src/jets/cold.rs, rust/ares/src/lib.rs, rust/ares/src/main.rs, rust/ares/src/mug.rs, rust/ares/src/serf.rs, rust/ares/src/trace.rs
@ashelkovnykov since this builds off the demo-debug work and in particular the cold-state matching, I'm targeting it at your demo-debug cleanup branch
This PR adds event-tracing profiling (-j in the king) to Ares.
TODO:
=> Event-based profiling

rust/ares/src/serf.rs
Caught by @philipquirk: when I added the extra frame push to preserve warm/cold state, I forgot to preserve the new Arvo state produced by the event.
=> serf: fix bug that would abandon arvo state

rust/ares/src/interpreter.rs
Nock 2 only comes from Hoon via .*, so we can assume it's never directly used to invoke jetted code.
=> jets: remove unnecessary jet check on Nock 2

rust/shell.nix
Couldn't run `cargo build` on m1 mac without this dependency.
=> devenv: add libiconv to shell.nix

rust/ares/src/mem.rs
This is intended to make writing code (e.g. jets) which needs to traverse a noun using the lightweight stack, but do so fallibly, more obviously stable.
=> 2stackz: add function to wrap a closure in frame push and pop

rust/ares/src/interpreter.rs, rust/ares/src/jets.rs, rust/ares/src/jets/warm.rs, rust/ares/src/main.rs, rust/ares/src/serf.rs, rust/ares/src/snapshot/double_jam.rs, rust/ares/src/snapshot/pma.rs, rust/ares/src/trace.rs
Pending custom string interpolation logic which allocates on the `NockStack`, disable all print statements which perform string interpolation.
With these changes applied, `status` boots to dojo without needing to set `assert_no_alloc` to `warn` level in `Cargo.toml`.
=> Disable all `eprintln!` calls which perform string interpolation

rust/ares/src/interpreter.rs, rust/ares/src/jets/cold.rs, rust/ares/src/jets/nock.rs, rust/ares/src/jets/warm.rs, rust/ares/src/serf.rs
Fixed a bug caught by @ashelkovnykov 
@ashelkovnykov please confirm my understanding. In particular:
=> virtualization: properly restore cold/warm states, cache, and scry stack when catching an error

rust/flake.nix, rust/nix/urcrypt.nix
Includes `autoconf-archive` in the `urcrypt.nix` file to support extra macros.
=> build: support latest `urcrypt`

rust/ares/src/jets.rs, rust/ares/src/jets/hot.rs, rust/ares/src/main.rs, rust/ares/src/serf.rs
Pass in the hot state as a parameter to `serf()`.
This enables distributing executables with other hot states by simply importing the ares crate, and passing in the additional hot state to the `serf()` call in the executable's `main()`.
=> Pass in hot state

.github/scripts/arch/get-runner-arch, .github/workflows/ares-shared.yml
Includes changes from and supersedes #169. This caches the nix build and cuts CI time to about 1 minute when cache is hit. Cache misses should only occur from devshell or cargo updates or changes. 
Full implementation of #165
=> CI: Cache nix and rust dependencies

rust/ares/src/jets/hot.rs, rust/ares/src/mem.rs, rust/ares/src/serf.rs
This prevents garbage from accumulating in the top frame, while also permitting us to preserve stuff between events there.
Once the PMA is merged this will allow us to retain the warm and hot states on the stack.
Implements #173
=> 2stackz: gc top frame by flipping polarity

rust/ares/src/jets/bits.rs
`jet_rev` had an issue with the indirect atom case. `IndirectAtom::new_raw` would normally be fine since we normalize, but since we're reversing endianness, we end up using the extra space. So the fix is to use `IndirectAtom::new_raw_bytes` instead.
I've also added a test case that catches this, which fails for the previous version.
=> jets: fix jet_rev

rust/ares/src/trace.rs
Tracing is too slow to use because it calls fsync nonstop.
=> don't fsync on every nock event while tracing

rust/ares_pma/c-src/btest.c, rust/ares_pma/c-src/btree.c
Makes the required changes to extend the PMA's backing file when allocation space is exceeded.
Includes a test in `btest.c` to validate this behavior. Other tests also exercise it (though don't perform file size validation because they were written to test different behavior)
=> PMA file extension

rust/ares_pma/c-src/btest.c, rust/ares_pma/c-src/btree.c
=> PMA node partition striping and file extension

rust/ares/Cargo.lock, rust/flake.nix
Fix the Nix build (separate PR later will enable static builds)
=> nix: remove glibc.static package that interferes with builds

rust/flake.nix
The mac x86 build fails because the cargo-watch build fails with some weird build error inside the quartz framework headers. This fixes the build by excluding cargo-watch.
=> remove cargo-watch for darwin-x86 because it doesn't build

rust/ares_pma/c-src/btree.c
use-after-free was responsible for crash
=> pma: clear pending_flist after completion of _pending_flist_merge

rust/ares/src/interpreter.rs, rust/ares/src/mem.rs
An OOM nondeterministic error can cause exit() to begin with a frame in copying mode. This causes an assertion failure when we allocate a cell for the stack trace. 
This PR does not yet handle recursive OOMing (i.e. OOMing when we are making a stack trace) which should be handled, but it does handle the case of OOMing during a `preserve()`.
=> interpreter: check for copying flag in exit

rust/ares/src/flog.rs, rust/ares/src/lib.rs
This adds the ability to do debugging printfs, formatted using Rust format strings, by allocating outputs as cords on the Nockstack and sending them as %flog messages via Newt
=> add format-to-cord implementation and flog! macro

rust/ares_pma/c-src/btest.c, rust/ares_pma/c-src/btree.c
There was a regression introduced with partition striping that caused problems on restore due to node partitions incidentally getting mapped anonymous rather than to the backing file
=> pma: fix regression on restore

rust/sword/src/hamt.rs
I just compared with what the MutHamt does. It makes the HamtIterator test pass but I am still working on seeing if this breaks any NockApps.
=> fix hamt insert()

rust/sword/src/jets/nock.rs
=> mook: re-enable stack traces for %mean hints

rust/sword/src/interpreter.rs
Interpret the `%bout` hint to time the wrapped Nock and report the elapsed time.
=> Implement %bout static hint

rust/sword/Cargo.toml, rust/sword/src/mem.rs
=> Malloc NockStack
